### PR TITLE
Added travis template

### PR DESCRIPTION
**Pull request by LanderU**

### CODE REVIEW

**Comment by LanderU** [comment]
I'll finish the CI stuff and then we can test it.

**Comment by nzlz** [comment]
@LanderU I made many changes related to linder errors https://github.com/AcutronicRobotics/gym-gazebo2/pull/6/commits/39886ba916a46a07befcec8f43bbc4c430986f67

Maybe we could consider reverting that commit and relaxing the linder rules? I see you are adding some exceptions already.

**Comment by LanderU** [comment]
> Maybe we could consider reverting that commit and relaxing the linter rules? I see you are adding some exceptions already.

I've more or less the linter problem fixed.

**Comment by LanderU** [comment]
Yes, do not merge it please.

**Comment by LanderU** [comment]
This first approach is ready to be merged: https://travis-ci.org/AcutronicRobotics/gym-gazebo2/builds/515236360

**Pull request merged**
